publish:
  whoami: asf-site
  
github:
  description: "Apache Submarine website"
  homepage: https://submarine.apache.org/
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
