publish:
  whoami: asf-site
  
github:
  description: "Apache Submarine"
  homepage: https://submarine.apache.org/
  labels:
    - apache
    - submarine
    - machine learning

github:
  enabled_merge_buttons:
    # enable squash button:
    squash:  false
    # enable merge button:
    merge:   false
    # disable rebase button:
    rebase:  false
